server:
  port: 8083

spring:
  application:
    name: notification-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            use:
              type:
                headers: false
            trusted:
              packages: "*"
            value:
              default:
                type: com.nexpay.notificationservice.entity.Transaction

    template:
      default-topic: transaction-events

