server:
  port: ${SERVER_PORT}

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          routes:
            # User Service - Authentication endpoints (no rate limiting)
            - id: user-service-auth
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/auth/**

            # User Service - API endpoints
            - id: user-service-api
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/api/users/**

            # Wallet Service
            - id: wallet-service
              uri: ${WALLET_SERVICE_URL}
              predicates:
                - Path=/api/wallets/**

            - id: transaction-service
              uri: ${TRANSACTION_SERVICE_URL}
              predicates:
                - Path=/api/transaction/**
              # Rate Limiter
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1

            # transaction microservice route
            - id: reward-service
              uri: ${REWARD_SERVICE_URL}
              predicates:
                - Path=/api/rewards/**
              # Rate Limiter
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1

            # notification microservice route
            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL}
              predicates:
                - Path=/api/notify/**
              # Rate Limiter
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1

    # HTTP Request Limits
    httpclient:
      max-initial-line-length: 4096
      max-header-size: 8192

    filters:
      - name: RequestSize
        args:
          maxSize: 1MB

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}